Домашнее задание 1
iskanaa3/2018-FS-11-Frontend-Akmanov pull request #1
Opened 2018-10-13 16:21 UTC by iskanaa3

Сделал дз1

2018-10-13 16:29 UTC, martinkomitsky requested changes
1. Не присылать больше дз с не всеми выполненными условиями - перечитать задание и сделать все пункты
2. Не присылать PR с конфликтами - разрешить конфликт
3. Выполнить требования, которые я уже 500 раз озвучил всем:
![image](https://user-images.githubusercontent.com/14847018/46907630-231ef500-cf1e-11e8-8317-a5ef039bc2fe.png)
4. Иметь ввиду, что в package.json должны быть npm скрипты, которые делают сборку и проверку линтером. Если линтер будет выдавать ошибку - снижу балл

2018-10-13 19:14 UTC, iskanaa3 commented
А сейчас?

2018-10-14 10:36 UTC, martinkomitsky commented
а что сейчас? Пункт 3.3 не готов, 4 тоже не вижу

2018-10-14 10:37 UTC, martinkomitsky requested changes
Нужно доделать

2018-10-16 20:57 UTC, martinkomitsky commented
@iskanaa3 будут фиксы??

2018-11-28 09:47 UTC, martinkomitsky commented
нет изменений, думаю, тут с концами

2018-11-28 09:47 UTC, closed without merging